### ISSUE TITLE
warnings when building with xcode 7

### ISSUE THREAD

**Issue by tspent** [tapdaq/tapdaq-ios-sdk#1]
Using the latest tapdaq sdk (v 0.94)
![screen shot 2015-09-28 at 1 14 42 pm](https://cloud.githubusercontent.com/assets/3499667/10133024/ef8f11cc-65e2-11e5-9463-0cb5e5fe43d2.png)

**Comment by nickreffitt** [comment]
Hi @tspent thanks for notifying us of this issue, we will investigate the problem and get a patch out asap

**Comment by nickreffitt** [comment]
Hi @tspent I have pushed a [new release](https://github.com/tapdaq/tapdaq-ios-sdk/releases/tag/0.9.5) which fixes the issue on our side, let me know if this works for you.

**Comment by tspent** [comment]
Hi @nickreffitt thanks for your quick reply. Works now!
