### ISSUE TITLE
Feature Request: Tapdaq for Messages Extension

### ISSUE THREAD

**Issue by evandelaney** [tapdaq/tapdaq-ios-sdk#3]
As a developer looking for alternative ways to monetize and cross promote my iMessage apps, I would like to be able to use the Tapdaq framework to bring native ads into my `MSMessagesAppViewController` subclass.

@nickreffitt I'm not sure if this is on the roadmap or even a consideration, but just about have it working...
- In `willBecomeActive(with:)` do the usual Tapdaq singleton setup and call `launch()`
- In `viewWillAppear(_:)` call `loadNativeAdvert(for:)`
- Setup a view with the native advert
- Call `triggerClick(_:)` and pass the ad. Safari launches, but all hell breaks loose! 😆 

Happy to help in any way. Thanks!

**Comment by nickreffitt** [comment]
Hey @evandelaney thanks for opening the ticket, I'll have a chat with @agarwalmukund tomorrow about it and let you know what we can do to accommodate.

**Comment by agarwalmukund** [comment]
Hi @evandelaney 
Thank you for reaching out. 
We will investigate and add support for iMessage app ads via native ads to our roadmap in the coming months.
Kind regards,
Mukund
