### ISSUE TITLE
Wrong quotes in podspec

### ISSUE THREAD

**Issue by disabled** [tapdaq/tapdaq-ios-sdk#4]
In lines:
```
s.version      = “1.2.0”
...
s.source       = { :git => "https://github.com/tapdaq/tapdaq-ios-sdk.git", :tag => “1.2.0” }
```
There should be " instead of ”
Cocoapods (1.0.1) is unable to parse spec because of this.

**Comment by agarwalmukund** [comment]
Thank you for pointing that out. I have fixed it now. 

Kind regards,
Mukund

**Comment by agarwalmukund** [comment]
Cocoapods have been correctly updated now. 
Please let us know if you run into any further issue.

Thank you,
Mukund
