### ISSUE TITLE
None of the delegate methods work

### ISSUE THREAD

**Issue by erebar** [tapdaq/tapdaq-ios-sdk#6]
Hello, is this only a problem I'm having? or everything works for you? Please let me know if they work when you test it because none of the delegate methods are firing for me except didFailToDisplayInterstitial

I'm using sdk 2.6.0.

Thanks

**Comment by agarwalmukund** [comment]
Hi @erebar 

It's working for us.
Can you please send me the email address linked to your Tapdaq account?
I will test it further using your credentials.

Thank you,
Mukund

**Comment by erebar** [comment]
Hello Mukund, its rwuapps@gmail.com

**Comment by agarwalmukund** [comment]
Hi @erebar,

Thank you. Which app are you currently working?

Kind regards,
Mukund

**Comment by erebar** [comment]
I'm testing adding the ios sdk directly on the exported unity project because the unity sdk for ios doesn't work either (this confirmed in the unity sdk page: https://github.com/tapdaq/unity-plugin/issues/9). Its the Mannequin game for ios. I've followed all your wiki directions and the sdk is starting, the only problem is that none of the delegate methods are firing.

**Comment by nickreffitt** [comment]
Hi @erebar, did you register a Placement Tag when attempting to display the interstitial? To register a placement tag, then display an interstitial for that placement tag, please see [the following docs](https://tapdaq.com/docs/unity-plugin/Interstitial)

**Comment by erebar** [comment]
Hi, yes I did. The problem is not even the placements, yeah they don't show but I wonder why the delegate methods are not firing. Ive used [(Tapdaq*)[Tapdaq sharedSession] setDelegate:self]; and none are firing except didFailToDisplayInterstitial but only when I call showInterstitialForPlacementTag

**Comment by nickreffitt** [comment]
Hi @erebar we've checked your account, and can see that your URL promotion has tablet creative uploaded only, this means you won't see any interstitial on an iPhone, but if you switch to an iPad test device, you should see the interstitial appear. If you would like to have your creative appear on an iPhone, simply upload more creative to your URL promotion.

Let me know if you hit any other issues.

Nick
