### ISSUE TITLE
Main thread locking

### ISSUE THREAD

**Issue by disabled** [tapdaq/tapdaq-ios-sdk#7]
Looks like SDK is querying external device IP address synchronously, which leads to noticeable lockups on poor internet connection.

![screen shot 2017-01-16 at 13 16 11](https://cloud.githubusercontent.com/assets/352526/21975928/f5362cc8-dc01-11e6-8fda-ffb1813a90c5.png)

**Comment by nickreffitt** [comment]
Hi @disabled - thank you for bringing this to our attention, we will remove that external dependency entirely and get a fix out in a few hours.

Nick

**Comment by agarwalmukund** [comment]
Hi @disabled, 
We have released v4.2.0 which contains the fix for this.
Please let us know if there are any further issues.
Thank you,
Mukund
