### ISSUE TITLE
Can't get cross-promo ad

### ISSUE THREAD

**Issue by disabled** [tapdaq/tapdaq-ios-sdk#8]
On 4.1.0 we can't seem to be able to get cross-promo ads, while mediation works fine.

After trying to load an ad placement with cross-promo associated with it, didFailToLoadInterstitialForPlacementTag: delegate method is called every second or so.

Looking at network log, seems like SDK is constantly fetching cross-promo graphics during this:
GET https://tapdaq-adverts.storage.googleapis.com/interstitial/900x1600/5824e7255a9e83584edf1877.png
   ← 200 image/png 503.11k 1.01s
GET https://tapdaq-adverts.storage.googleapis.com/interstitial/900x1600/5824e7255a9e83584edf1877.png
   ← 200 image/png 503.11k 1.03s
GET https://tapdaq-adverts.storage.googleapis.com/interstitial/900x1600/5824e7255a9e83584edf1877.png
   ← 200 image/png 503.11k 1.09s
GET https://tapdaq-adverts.storage.googleapis.com/interstitial/900x1600/5824e7255a9e83584edf1877.png
   ← 200 image/png 503.11k 1.31s
GET https://tapdaq-adverts.storage.googleapis.com/interstitial/900x1600/5824e7255a9e83584edf1877.png
   ← 200 image/png 503.11k 2.13s
GET https://tapdaq-adverts.storage.googleapis.com/interstitial/900x1600/5824e7255a9e83584edf1877.png
   ← 200 image/png 503.11k 1.95s
GET https://tapdaq-adverts.storage.googleapis.com/interstitial/900x1600/5824e7255a9e83584edf1877.png
   ← 200 image/png 503.11k 2.53s

**Comment by nickreffitt** [comment]
Hi @disabled - could you send me an example of your integration to support@tapdaq.com please, this will help us replicate the issue our end

Thanks 

Nick

**Comment by disabled** [comment]
@nickreffitt, sent it to support email.

**Comment by nickreffitt** [comment]
Got it, thanks very much, we will take a look now

**Comment by agarwalmukund** [comment]
Hi @disabled, 
We have released v4.2.0 which contains the fix for this.
Please let us know if there are any further issues.
Thank you,
Mukund
