### ISSUE TITLE
Cross promotion

### ISSUE THREAD

**Issue by erebar** [tapdaq/tapdaq-ios-sdk#9]
Ive updated to version 4.6.0 and now I'm not getting url cross promotions.

I was using version 3.0.0 and it was working. Now all I get is:
[Tapdaq SDK] Ad Network unityads FW not present in your app!

I'm not using any of the adapters, I just want cross promotions.

**Comment by nickreffitt** [comment]
Hi @erebar I'll take a look at this right away

Could you let me know which application you are testing with?

Thanks

Nick

**Comment by erebar** [comment]
Hi Nick, the application is:

Awesome Donut Ice Cream Cake Breakfast Shop Maker
My user is jimmyonapp@gmail.com

Thanks

**Comment by nickreffitt** [comment]
Hi @erebar thanks very much.

We will take a look at this right away and get back to you in the next few hours with an update.

**Comment by agarwalmukund** [comment]
Hi @erebar,

We have checked you dashboard settings and everything is set up correctly.
We are able to show the cross promo ad on boot up and manually via the following test app:
https://github.com/tapdaq/tapdaq-ios-sdk/wiki/Use-Cases#example-project

Please check the latest SDK implementation in the above link and let us know if there are any further issues.

Thank you,
Mukund

**Comment by erebar** [comment]
Its working now, thanks. I have a suggestion though: 

Update or remove that video you have in the link. Your boot up ad video is OLD. It doesn't say that you need to load the interstitial first with "loadInterstitialForPlacementTag". It tells you to use "hasInterstitialsAvailableForOrientation" when that method is never called and you need to use "didLoadInterstitialForPlacementTag" instead. Updating that will surely help a lot of people.

**Comment by nickreffitt** [comment]
Hi @erebar thanks for the feedback, we've removed this for now. 

We're reviewing our docs, tutorials, and example integrations on all platforms, so that we can provide a much better integration experience for developers like yourself. 

You will definitely see improvements in the next week or so.

All the best
Nick
